version: '3'
services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"
